package CalculatorProject;

/**
 * Created by emilybutte on 9/13/16.
 */
public enum Operations {
    ADD,SUB,MULTIPLY,DIVIDE,SQUAREROOT,SQUARE,INVERSE,EXPONENTIAL,INV,SAVE,RETRIEVE,MRESET,
    SIN,COS,TAN,INVSINE,INVCOS,INVTAN,LOG,INVLOG,LN,EX,FACT,DISPLAY,UNITS,OFF,MENU,CLEAR
}